---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]
 
  - name: apt upgrade packages
    apt:
      upgrade: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]
      
  - name: apk update for Alpine
    apk:
      update_cache: yes
    when: ansible_distribution == "Alpine"

  - name: apk upgrade for Alpine
    apk:
      upgrade: yes
    when: ansible_distribution == "Alpine"
